// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nexufwwknzzyzgxmzdom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5leHVmd3drbnp6eXpneG16ZG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjA1NjUsImV4cCI6MjA2ODQzNjU2NX0.9q8a-A9sE5PY0IcKffvuD51IEo-dGy8XizGD-_G912Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);